Leaderboard embed
Cortex-Development/cortex-bot pull request #27
Opened 2023-05-12 20:01 UTC by Scyye

Updated LeaderboardCommand to use an embed. rather than a message; removing problems with using the command in forums, allowing you to add 15 people to any forum thread.

2023-05-12 20:02 UTC, Scyye commented
I have literally - clue how to use github.
I just made a pull request to my fork. and i made like 4 forks. i hope that doesnt interfere with anyone else

2023-08-23 00:58 UTC, KodySimpson requested changes
Needs fixing

2023-08-23 00:58 UTC, KodySimpson commented on src/main/java/dev/cortex/cortexbot/commands/LeaderboardCommand.java
> +                .toList();
Needs to be collect instead of toList to avoid immutability exception

2023-08-23 00:58 UTC, KodySimpson commented on src/main/java/dev/cortex/cortexbot/commands/LeaderboardCommand.java
> +            builder.addField(nameString.toString(), top.get(i) + "pts", false);
You are doing top.get(i) here on an object rather than primitive value

2023-08-23 00:58 UTC, KodySimpson commented on src/main/java/dev/cortex/cortexbot/commands/LeaderboardCommand.java
> +            builder.addField(nameString.toString(), top.get(i) + "pts", false);
![image](https://github.com/Cortex-Development/cortex-bot/assets/77004702/c6e86aad-518b-46f6-8adf-07ad74cbb1d3)

2023-08-23 02:29 UTC, Scyye commented
Alright, ill start work on that.

Could you accept my friend request?
I would like to have a conversation

2023-09-09 02:15 UTC, closed without merging